config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :rooms, only: [ :index, :show, :new, :create, :destroy ] do
    member do
      patch :start
      patch :finish
    end

    resources :room_players do
        post :roll_dice, on: :member
    end
  end
  post "rooms/:id/join", to: "room_players#join", as: "join_room"


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "rooms#index"

  # Use Cable for channels multiplayer
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dice.rb
class Dice
  DEFAULT_SIDES = 6

  attr_reader :sides

  def initialize(sides = DEFAULT_SIDES)
    @sides = sides
  end

  def roll
    rand(1..sides)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :turns
end

app/models/room.rb
class Room < ApplicationRecord
  enum :status, { waiting: 0,
                  rolling_for_order: 1,
                  tiebreak_for_order: 2,
                  playing: 3,
                  finished: 4 }

  has_many :room_players, dependent: :destroy
  has_many :users, through: :room_players
  has_many :turns, dependent: :destroy

  def current_player
    return nil if current_turn.nil?
    room_players.find_by(turn_order: current_turn)
  end
end

app/models/room_player.rb
class RoomPlayer < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :turns
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :room
  belongs_to :room_player
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  has_many :room_players
  has_many :rooms, through: :room_players
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :track_user_activity
 before_action :store_current_user_id, if: -> { controller_name == "sessions" && action_name == "destroy" }

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def store_current_user_id
    session[:last_user_id] = current_user&.id
  end

  def after_sign_in_path_for(resource)
    broadcast_update_users_online
    super
  end

  def after_sign_out_path_for(resource_or_scope)
    user_id = session.delete(:last_user_id)
    AppRedisClient.instance.redis.del("user:#{user_id}:online")
    broadcast_update_users_online

    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name ])
  end

  private

  def track_user_activity
    return unless user_signed_in?

    now = Time.current
    user_key = "user:#{current_user.id}:online"
    redis = AppRedisClient.instance.redis
    previously_online = redis.exists(user_key)

    redis.setex(user_key, 5.minutes.to_i, now.to_s)

    if current_user.last_seen_at.nil? || current_user.last_seen_at < 1.minutes.ago
      current_user.update_column(:last_seen_at, now)
    end

    unless previously_online
      broadcast_update_users_online
    end
  end
  def broadcast_update_users_online
    Turbo::StreamsChannel.broadcast_replace_to(
      "online_users",
      target: "online_users",
      partial: "online_users/count"
    )
  end
end

app/controllers/room_players_controller.rb
class RoomPlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room_player, only: [ :roll_dice ]

  def join
    room = Room.find(params[:id])

    unless room.room_players.exists?(user_id: current_user)
      turn_order = room.room_players.count
      room.room_players.create(user: current_user, score: 0, turn_order: turn_order)
    end

    Turbo::StreamsChannel.broadcast_replace_to(
          "room_#{room.id}",
          target: "players",
           partial: "rooms/players_list",
          locals: { room: room, current_user: current_user }
    )

    Turbo::StreamsChannel.broadcast_replace_to(
          "room_#{room.id}",
          target: "current_user_actions",
           partial: "rooms/current_user_actions",
          locals: { room: room, current_user: current_user }
    )

    respond_to do |format|
      format.html { redirect_to room_path(room) }
      format.turbo_stream { head :ok }
    end
  end

  def roll_dice
    unless @room_player.user == current_user
      head :forbidden and return
    end

    @room = @room_player.room
    game = GameManager.for(@room)

    game.roll_dice(current_user)
    game.save
    game.evaluate_rolls_and_update_state
    game.broadcast_room_update(current_user)

    respond_to do |format|
      format.turbo_stream { head :ok }
      format.html { redirect_to game.room }
    end
  end

  private

  def set_room_player
    @room_player = RoomPlayer.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [ :show, :start, :finish, :destroy ]

  include ActionView::RecordIdentifier

  def index
    @rooms = Room.all
    @active_rooms = Room.where.not(status: :finished)
    @finished_rooms = Room.where(status: :finished)
  end

  def show
    @game = GameManager.for(@room)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      @room.room_players.create(user: current_user, score: 0, turn_order: 0)
      redirect_to @room
    else
      render :new
    end
  end

  def start
    @game = GameManager.for(@room)

    if @room.waiting?
      @game.start_turn_order_phase!
    end

    @game.broadcast_room_update(current_user)

    respond_to do |format|
      format.turbo_stream { head :ok }
      format.html { redirect_to @room }
    end
  end

  def finish
    @game = GameManager.for(@room)
    if @room.playing?
      @game.finished!
    end

    @game.broadcast_room_update(current_user)

    respond_to do |format|
      format.turbo_stream { head :ok }
      format.html { redirect_to @room }
    end
  end

  def destroy
    Turbo::StreamsChannel.broadcast_remove_to(
      "room_#{@room.id}",
      target: dom_id(@room)
    )

    @room.destroy

    respond_to do |format|
      format.turbo_stream { redirect_to rooms_path, status: :see_other }
      format.html { redirect_to rooms_path, notice: "Sala eliminada correctamente." }
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :status)
  end

  def set_room
    @room = Room.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to rooms_path, alert: "La sala ya no existe"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_players_helper.rb
module RoomPlayersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Quiz Game" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (ymake sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <turbo-frame id="online_users">
        <%= render "online_users/count" %>
      </turbo-frame>
      <%= current_user.name %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %> <% end %>
    <%= yield %>
  </body>
</html>

app/views/online_users/_count.html.erb
<p> Usuarios conectados: <span id="online-users-count"><%= OnlineUsers.count %></span></p>

app/views/room_players/roll_dice.js.erb
const container = document.getElementById("dice-result-<%= @room_player.id %>");
container.innerHTML = "<%= j image_tag('dice_roll.gif', alt: 'Rolling...', width: 100) %>";

setTimeout(function() {
  container.innerHTML = "<strong> Dado <%= @room_player.dice_roll %></strong>";
}, 3000);

app/views/rooms/_answer_form.html.erb
<% if room_player.user == current_user %>
  <% form_with model: [room_player, :answer], url: room_player_answer_path(room_player), local: false do |f| %>
    <% f.text_field :content, placeholder: "Tu respuesta…" %>
    <% f.submit "Responder" %>
  <% end %>
<% end %>

app/views/rooms/_current_user_actions.html.erb
<% if room.waiting? %>
    <% unless room.room_players.exists?(user_id: current_user.id) %>
      <%= button_to 'Unirme a esta sala', join_room_path(room), method: :post %>
    <% end %>
<% elsif room.rolling_for_order? || room.tiebreak_for_order? %>
    <% if room_player && !room_player.dice_roll.present? %>
      <%= button_to "Tirar dado",
        roll_dice_room_room_player_path(room.id, room_player.id),
        method: :post,
        remote: true,
        id: "roll-dice-btn-#{room_player.id}" %> 
    <% end %>
 <% end %>

app/views/rooms/_players_list.html.erb
<ul id="players-list">
    <% room.room_players.includes(:user).each do |rp| %>

    <li class="player-item player-card <%= 'active' if rp == room.current_player %>">
        <span class="player-name"><%= rp.user.name %></span>
        <span class="player-score"> - Puntos: <%= rp.score %></span>
        <span class="player-turn"> - Turno: <%= rp.turn_order %> -</span>
        <% if room.rolling_for_order? || room.tiebreak_for_order? %>
        <span id="dice-result-<%= rp.id %>">
            <% if rp.dice_roll.present? %>
              Dado <%= rp.dice_roll %>
            <% else %>
              <%= image_tag 'dice_roll.gif', alt: 'Rolling...', width: 25, height: 25 %>
            <% end %>
        </span>
        <% end %>
    </li>
    <% end %>
</ul>

app/views/rooms/_question.html.erb
<p><strong><% question.text %></strong></p>

<div class="media-content">
  <% if question.image_url.present? %>
    <% image_tag question.image_url, style: "max-width: 300px;" %>
  <% end %>

  <% if question.audio_url.present? %>
    <audio controls>
      <source src="<%= question.audio_url %>">
    </audio>
  <% end %>

  <% if question.video_url.present? %>
    <video width="400" controls>
      <source src="<%= question.video_url %>">
    </video>
  <% end %>
</div>

app/views/rooms/_question_box.html.erb
<div class="question-box">
  <% if room.current_player&.user == current_user %>
    <h2>Tu turno: responde a la siguiente pregunta</h2>
    <%# render "rooms/question", question: @room.current_question %>
    <%# render "rooms/answer_form", room_player: @room_player %>
    <p>Buscando Pregunta al azar de la dificultad seleccionada...</p>
  <% else %>
    <h2>Turno de <%= room.current_player&.user&.name %>. Espera tu turno…</h2>
  <% end %>
</div>

app/views/rooms/_status_panel.html.erb
 <p class="status <%= room.status %>"><%= room.status.humanize  %></p>
  
  <% if room.waiting? %>
    <%= button_to "Empezar partida", start_room_path(room), method: :patch, data: { turbo_confirm: "Empezar partida?" } %>
  <% elsif room.rolling_for_order? || room.tiebreak_for_order? %>
    <% if room.tiebreak_for_order? %>
          <p>🎲 Empate entre <%= room.room_players.where.not(dice_roll: nil).map { |p| p.user.name }.join(", ") %>. Solo ellos vuelven a tirar.</p>
    <% else %>
      <% if room.room_players.all? { |p| p.dice_roll.present? } %>
        <p> El jugador <%= room.current_player&.user&.name %> empieza la partida.</p>
      <% else %>
        <p> ⏳ Esperando tiradas de los demas jugadores...</p>
      <% end %>
    <% end %>
  <% elsif room.playing? %>
    <% if room.current_player.user_id == current_user.id %>
      <p> Tiempo restante: </p>
      <%= button_to "Finalizar partida", finish_room_path(room), method: :patch, data: {turbo_confirm: "Finalizar partida?" } %>
    <% else %>
      <h2>Turno de <%= room.current_player.user.name %></h2>
    <% end %>
  <% elsif room.finished? %>
    <%= button_to "Eliminar sala", room_path(room), method: :delete, data: { turbo_confirm: "Eliminar sala?" } %>
  <% end %>

app/views/rooms/index.html.erb
<h1>Salas de Juego</h1>

<h2> Salas Activas </h2>

<ul>
  <% @active_rooms.each do |room| %>
    <li>
      <%= link_to room.name, room_path(room) %> - Estado: <%= room.status %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Crear nueva sala', new_room_path %>

<br />
<h2> Salas finalizadas </h2>

<ul>
  <% @finished_rooms.each do |room|  %>
    <li>
      <%= link_to room.name, room_path(room) %>
    </li>
  <% end %>
</ul>

app/views/rooms/new.html.erb
<h1>Crear una nueva sala</h1>
  <%= form_with model: @room, local: true do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <%= form.hidden_field :status, value: :waiting %>
    <%= form.submit 'Crear sala' %>
  <% end %>

<br/>

<div class="link">
  <%= link_to "Volver a Salas", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= turbo_stream_from "room_#{@room.id}" %>
<%= turbo_stream_from current_user %>
<div class="room-header">
  <h1>Sala: <%= @room.name %></h1>
  <%= link_to "Volver a Salas", rooms_path %>  
</div>
<div class="players">
  <h2>Jugadores</h2>
  <div id="players">
    <%= render :partial => 'players_list', locals: { room: @room } %>
  </div>
</div>
<div class="current_user_actions" id="current_user_actions">
  <%= render :partial => 'current_user_actions', locals: { room: @room, room_player: @room.room_players.find_by(user: current_user) } %>
</div>

<% if @room.playing? %> 
  <div id="question-box">
    <%= render :partial => 'question_box', locals: { room: @room, room_player: @room.room_players.find_by(user: current_user) } %>
  </div>
<% end %>

<div class="status-panel">
  <h3>Estado de la sala</h3>
  <div id="status-panel">
    <%= render partial: "rooms/status_panel", locals: { room: @room, current_user: current_user } %>
  </div>
</div>